from typing import List, Dict

PLACES_DB: List[Dict] = [
    {"name": "Eiffel Tower", "city": "Paris", "country": "FR", "tags": ["history", "architecture"]},
    {"name": "Louvre Museum", "city": "Paris", "country": "FR", "tags": ["museum", "art"]},
    {"name": "Colosseum", "city": "Rome", "country": "IT", "tags": ["history", "architecture"]},
    {"name": "Acropolis", "city": "Athens", "country": "GR", "tags": ["history", "culture"]},
    {"name": "Bondi Beach", "city": "Sydney", "country": "AU", "tags": ["beach", "surfing"]},
    {"name": "Statue of Liberty", "city": "New York", "country": "US", "tags": ["history", "monument"]},
    {"name": "Mount Fuji", "city": "Fujinomiya", "country": "JP", "tags": ["nature", "mountain"]},
    {"name": "Grand Canyon", "city": "Grand Canyon", "country": "US", "tags": ["nature", "park"]},
     {"name": "Great Wall of China", "city": "Beijing", "country": "CN", "tags": ["history", "architecture"]},
    {"name": "Machu Picchu", "city": "Cusco", "country": "PE", "tags": ["history", "mountain"]},
    {"name": "Christ the Redeemer", "city": "Rio de Janeiro", "country": "BR", "tags": ["monument", "religion"]},
    {"name": "Taj Mahal", "city": "Agra", "country": "IN", "tags": ["history", "architecture"]},
    {"name": "Pyramids of Giza", "city": "Cairo", "country": "EG", "tags": ["history", "monument"]},
    {"name": "Niagara Falls", "city": "Niagara Falls", "country": "US", "tags": ["nature", "waterfall"]},
    {"name": "Santorini", "city": "Santorini", "country": "GR", "tags": ["island", "beach"]},
    {"name": "Stonehenge", "city": "Amesbury", "country": "UK", "tags": ["history", "mystery"]},
    {"name": "Angkor Wat", "city": "Siem Reap", "country": "KH", "tags": ["history", "temple"]},
    {"name": "Burj Khalifa", "city": "Dubai", "country": "AE", "tags": ["architecture", "skyscraper"]},
    {"name": "Sydney Opera House", "city": "Sydney", "country": "AU", "tags": ["architecture", "culture"]},
    {"name": "Petra", "city": "Petra", "country": "JO", "tags": ["history", "archaeology"]},
    {"name": "Banff National Park", "city": "Banff", "country": "CA", "tags": ["nature", "park"]},
    {"name": "Table Mountain", "city": "Cape Town", "country": "ZA", "tags": ["nature", "mountain"]},
    {"name": "Iguazu Falls", "city": "Foz do Iguaçu", "country": "BR", "tags": ["nature", "waterfall"]},
    {"name": "Serengeti National Park", "city": "Serengeti", "country": "TZ", "tags": ["nature", "safari"]},
    {"name": "Great Barrier Reef", "city": "Cairns", "country": "AU", "tags": ["nature", "reef"]},
    {"name": "Chichen Itza", "city": "Yucatan", "country": "MX", "tags": ["history", "archaeology"]},
    {"name": "Hagia Sophia", "city": "Istanbul", "country": "TR", "tags": ["history", "religion"]},
    {"name": "Versailles Palace", "city": "Versailles", "country": "FR", "tags": ["history", "palace"]},
    {"name": "Alhambra", "city": "Granada", "country": "ES", "tags": ["history", "palace"]},
    {"name": "Mount Kilimanjaro", "city": "Moshi", "country": "TZ", "tags": ["nature", "mountain"]},
    {"name": "Yellowstone National Park", "city": "Wyoming", "country": "US", "tags": ["nature", "geysers"]},
    {"name": "Mount Everest Base Camp", "city": "Lukla", "country": "NP", "tags": ["mountain", "adventure"]},
    {"name": "Hawaii Volcanoes National Park", "city": "Hilo", "country": "US", "tags": ["nature", "volcano"]},
    {"name": "Sagrada Familia", "city": "Barcelona", "country": "ES", "tags": ["architecture", "religion"]},
    {"name": "Prague Castle", "city": "Prague", "country": "CZ", "tags": ["history", "castle"]},
    {"name": "Kremlin", "city": "Moscow", "country": "RU", "tags": ["history", "politics"]},
    {"name": "Neuschwanstein Castle", "city": "Füssen", "country": "DE", "tags": ["castle", "architecture"]},
    {"name": "Matterhorn", "city": "Zermatt", "country": "CH", "tags": ["mountain", "nature"]},
    {"name": "Mount Denali", "city": "Alaska", "country": "US", "tags": ["mountain", "nature"]},
    {"name": "Blue Lagoon", "city": "Grindavik", "country": "IS", "tags": ["spa", "nature"]},
    {"name": "Galápagos Islands", "city": "Puerto Ayora", "country": "EC", "tags": ["nature", "wildlife"]},
    {"name": "Salar de Uyuni", "city": "Uyuni", "country": "BO", "tags": ["nature", "desert"]},
    {"name": "Cinque Terre", "city": "La Spezia", "country": "IT", "tags": ["coast", "colorful"]},
    {"name": "Mount Etna", "city": "Catania", "country": "IT", "tags": ["nature", "volcano"]},
    {"name": "Lake Baikal", "city": "Irkutsk", "country": "RU", "tags": ["nature", "lake"]},
    {"name": "Pamukkale", "city": "Denizli", "country": "TR", "tags": ["nature", "hot_springs"]},
    {"name": "Great Ocean Road", "city": "Victoria", "country": "AU", "tags": ["road_trip", "coast"]},
    {"name": "Mount Athos", "city": "Mount Athos", "country": "GR", "tags": ["religion", "mountain"]},
    {"name": "Kruger National Park", "city": "Nelspruit", "country": "ZA", "tags": ["safari", "wildlife"]},
]

def get_places(interests: List[str], limit: int = 5) -> List[Dict]:
    interests_set = set(i.lower() for i in interests)
    filtered = [p for p in PLACES_DB if interests_set & set(t.lower() for t in p.get("tags", []))]
    return filtered[:limit]
